### ISSUE TITLE
SetTokens call in SessionsEvent sample doesn't expect SecurityTokenValidationException and terminates early

### ISSUE THREAD

**Issue by peteraritchie** [blowdart/idunno.Bluesky#55]
# Bug report 

### Describe the bug

It looks like `AtProtoAgent.SetTokens` started validating the passed tokens after SessionEvent sample was created.  SessionEvents.Program like 234 calls SetTokens without a try/catch expecting a `InvalidSessionException` once `AtProtoAgent.RefreshSession` is called.

### Expected behavior

I'd expect that the call to SetTokens would be guarded by a try/catch.

### Actual behavior

The call to SetTokens isn't guarded and results in the sample terminating early, dumping exception detail:
```
Unhandled exception: idunno.AtProto.SecurityTokenValidationException: The issued access token could not be validated.
   at idunno.AtProto.AtProtoAgent.SetTokens(String accessJwt, String refreshJwt, CancellationToken cancellationToken) in C:\Users\peter\src\oss\idunno.Bluesky\src\idunno.AtProto\AtProtoAgent.cs:line 1666
   at Samples.SessionEvents.Program.DemonstrateAgentEvents(String handle, String password, Uri proxyUri, CancellationToken cancellationToken) in C:\Users\peter\src\oss\idunno.Bluesky\samples\Samples.SessionEvents\Program.cs:line 234
   at Samples.SessionEvents.Program.<>c__DisplayClass0_0.<<Main>b__3>d.MoveNext() in C:\Users\peter\src\oss\idunno.Bluesky\samples\Samples.SessionEvents\Program.cs:line 71
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

### What operating system(s) are you using?

- [x] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] Other (specify below)

### Reproduction code

Run the SessionEvents sample with a valid handle and password.

**Comment by blowdart** [comment]
Ta :) This also exposed GetSessionResponse's json attributes went missing somewhere.

Ugh

**Comment by peteraritchie** [comment]
That was my next PR, with tests. It's just the c'tor attribute?

**Comment by blowdart** [comment]
Oh boy do I need deserializsation tests :) But I got it in f205adf1f2198f2e86e92f585b717a0b3e942458
